# Generated by Django 3.2.22 on 2023-11-07 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_onlineusers_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energy_storage_info',
            old_name='run_day222',
            new_name='run_day222333',
        ),
    ]
